### ISSUE TITLE
Creating log files is preventing docker-compose up from finishing

### ISSUE THREAD

**Issue by matthebs** [mortezaPRK/docker-php#1]
in docker.ample.
RUN mkdir -p /var/log/fpm/ && touch /var/log/nginx/php_error.log && chmod 777 /var/log/nginx/php_error.log

i get and error touch /var/log/nginx/php_error.log file or directory not found.

I created my LOG/nginx folder

Don't know what I'm doing wrong.
I put the .docker in my laravel project folder and changed the nginx config accordingly.

thanks.

**Comment by mortezaPRK** [comment]
I'm redesigning my repo. for now, use this commit '602811c062c9fe88a51627de143e22d31b860eab'
